/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TheGPU */

#ifndef _Included_TheGPU
#define _Included_TheGPU
#ifdef __cplusplus
extern "C" {
#endif
#undef TheGPU_maxQueries
#define TheGPU_maxQueries 1L
#undef TheGPU_maxBuffers
#define TheGPU_maxBuffers 10L
/*
 * Class:     TheGPU
 * Method:    init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     TheGPU
 * Method:    getQuery
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_getQuery
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     TheGPU
 * Method:    setInput
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_setInput
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     TheGPU
 * Method:    setOutput
 * Signature: (IIIIIII)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_setOutput
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     TheGPU
 * Method:    execute
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_execute
  (JNIEnv *, jobject, jint, jintArray, jintArray);

/*
 * Class:     TheGPU
 * Method:    free
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TheGPU_free
  (JNIEnv *, jobject);

/*
 * Class:     TheGPU
 * Method:    setKernelDummy
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_setKernelDummy
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     TheGPU
 * Method:    setKernelProject
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_setKernelProject
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     TheGPU
 * Method:    setKernelSelect
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_setKernelSelect
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     TheGPU
 * Method:    setKernelReduce
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_setKernelReduce
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     TheGPU
 * Method:    setKernelAggregate
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_setKernelAggregate
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     TheGPU
 * Method:    setKernelThetaJoin
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_TheGPU_setKernelThetaJoin
  (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
