/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_imperial_lsds_seep_multi_TheCPU */

#ifndef _Included_uk_ac_imperial_lsds_seep_multi_TheCPU
#define _Included_uk_ac_imperial_lsds_seep_multi_TheCPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_imperial_lsds_seep_multi_TheCPU
 * Method:    getNumCores
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_seep_multi_TheCPU_getNumCores
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_seep_multi_TheCPU
 * Method:    bind
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_seep_multi_TheCPU_bind
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_ac_imperial_lsds_seep_multi_TheCPU
 * Method:    unbind
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_seep_multi_TheCPU_unbind
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_seep_multi_TheCPU
 * Method:    getCpuId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_seep_multi_TheCPU_getCpuId
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
