/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU */

#ifndef _Included_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
#define _Included_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU_init
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
 * Method:    getQuery
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU_getQuery
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
 * Method:    setInput
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU_setInput
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
 * Method:    setOutput
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU_setOutput
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
 * Method:    execute
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU_execute
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
 * Method:    free
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU_free
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
 * Method:    setKernelIdentity
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU_setKernelIdentity
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
 * Method:    setKernelProjection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU_setKernelProjection
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
 * Method:    setKernelSelection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU_setKernelSelection
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU
 * Method:    setKernelReduction
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_streamsql_op_gpu_TheGPU_setKernelReduction
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
