# Master 
ip route add $ANDROID_MASTER_NET via $VMCORE_MASTER_VETH_IP dev $CORE_VMCORE_ETH

# Workers
ip route add $ANDROID_WORKER1_NET via $CORE_WORKER1_IP dev $CORE_MANET_ETH 
ip route add $ANDROID_WORKER2_NET via $CORE_WORKER2_IP dev $CORE_MANET_ETH 
ip route add $ANDROID_WORKER3_NET via $CORE_WORKER3_IP dev $CORE_MANET_ETH 
ip route add $ANDROID_WORKER4_NET via $CORE_WORKER4_IP dev $CORE_MANET_ETH 
ip route add $ANDROID_WORKER5_NET via $CORE_WORKER5_IP dev $CORE_MANET_ETH 
ip route add $ANDROID_WORKER6_NET via $CORE_WORKER6_IP dev $CORE_MANET_ETH 
