#
# CORE
# Copyright (c)2010-2012 the Boeing Company.
# See the LICENSE file included in this distribution.
#
''' Sample user-defined service.
'''

import os

from core.service import CoreService, addservice
from core.misc.ipaddr import IPv4Prefix, IPv6Prefix

class Android(CoreService):
    ''' This is a sample user-defined service. 
    '''
    # a unique name is required, without spaces
    _name = "Android"
    # you can create your own group here
    _group = "SEEP"
    # list of other services this service depends on
    _depends = ()
    # per-node directories
    _dirs = ()
    # generated files (without a full path this file goes in the node's dir,
    #  e.g. /tmp/pycore.12345/n1.conf/)
    _configs = ('android.sh', )
    # this controls the starting order vs other enabled services
    _startindex = 50
    # list of startup commands, also may be generated during startup
    _startup = ('sh android.sh',)
    # list of shutdown commands
    _shutdown = ()


    @classmethod
    def generateconfig(cls, node, filename, services):
        ''' Return a string that will be written to filename, or sent to the
            GUI for user customization.
        '''
    	seep_example_dir = "/home/acita14demo/dev/seep-ita/seep-system/examples/acita_demo_2015"

        cfg = "#!/bin/sh\n"
        cfg += "# auto-generated by Android (android.py)\n"
	cfg += "cp %s/core-emane/config/demo_env.sh .\n"%(seep_example_dir)
	cfg += "source demo_env.sh\n"
	cfg += "cp %s/core-emane/config/core-worker`hostname`-android-routes.sh .\n"%(seep_example_dir)
	cfg += "echo routes before:\n"
	cfg += "route\n"
	cfg += "./core-worker`hostname`-android-routes.sh\n"
	cfg += "echo routes after:\n"
	cfg += "route\n"

        return cfg

# this line is required to add the above class to the list of available services
addservice(Android)

