#
# CORE
# Copyright (c)2010-2012 the Boeing Company.
# See the LICENSE file included in this distribution.
#
''' Sample user-defined service.
'''

import os

from core.service import CoreService, addservice
from core.misc.ipaddr import IPv4Prefix, IPv6Prefix

class Worker(CoreService):
    ''' This is a sample user-defined service. 
    '''
    # a unique name is required, without spaces
    _name = "Worker"
    # you can create your own group here
    _group = "SEEP"
    # list of other services this service depends on
    _depends = ()
    # per-node directories
    _dirs = ()
    # generated files (without a full path this file goes in the node's dir,
    #  e.g. /tmp/pycore.12345/n1.conf/)
    _configs = ('worker.sh', )
    # this controls the starting order vs other enabled services
    _startindex = 50
    # list of startup commands, also may be generated during startup
    _startup = ('sh worker.sh',)
    # list of shutdown commands
    _shutdown = ()


    @classmethod
    def generateconfig(cls, node, filename, services):
        ''' Return a string that will be written to filename, or sent to the
            GUI for user customization.
        '''
    	seep_example_dir = "/home/acita14demo/dev/seep-ita/seep-system/examples/acita_demo_2015"
    	seep_jar = "seep-system-0.0.1-SNAPSHOT.jar"

        cfg = "#!/bin/sh\n"
        cfg += "# auto-generated by Worker (worker.py)\n"
	cfg += "pwd\n"
	cfg += "ls\n"
	cfg += "cp %s/lib/%s .\n"%(seep_example_dir, seep_jar)
	cfg += "cp %s/core-emane/config/watch-neighbours.sh .\n"%(seep_example_dir)
	cfg += "route\n"
	cfg += "touch /tmp/worker-nbrs.log\n"
	cfg += "./watch-neighbours.sh >> /tmp/worker-nbrs.log &\n"
	cfg += "echo Starting Worker on `hostname`\n"
	cfg += "java -jar %s Worker\n"%(seep_jar)

        return cfg

# this line is required to add the above class to the list of available services
addservice(Worker)

