#
# CORE
# Copyright (c)2010-2012 the Boeing Company.
# See the LICENSE file included in this distribution.
#
''' Sample user-defined service.
'''

import os

from core.service import CoreService, addservice
from core.misc.ipaddr import IPv4Prefix, IPv6Prefix

class FailureInjector(CoreService):
    ''' This is a sample user-defined service. 
    '''
    # a unique name is required, without spaces
    _name = "FailureInjector"
    # you can create your own group here
    _group = "SEEP"
    # list of other services this service depends on
    _depends = ()
    # per-node directories
    _dirs = ()
    # generated files (without a full path this file goes in the node's dir,
    #  e.g. /tmp/pycore.12345/n1.conf/)
    _configs = ('failure-injector.sh',)
    # this controls the starting order vs other enabled services
    _startindex = 101 
    #_starttime="10"
    # list of startup commands, also may be generated during startup
    _startup = ('sh failure-injector.sh',)
    # list of shutdown commands
    _shutdown = ()


    @classmethod
    def generateconfig(cls, node, filename, services):
        ''' Return a string that will be written to filename, or sent to the
            GUI for user customization.
        '''
        
        repo_dir = "%s/../../../../../.."%os.path.dirname(os.path.realpath(__file__))
        seep_example_dir = "%s/seep-system/examples/acita_demo_2015"%repo_dir
	
        cfg = "#!/bin/bash\n"
        cfg += "# auto-generated by FailureInjector\n"
        cfg += "cp %s/core-emane/vldb/config/run_failure_injector.py .\n"%(seep_example_dir)
        cfg += 'echo "Starting failure injector on node %d"\n'%node.objid
        #cfg += "./run_failure_injector.py --node n%d 1>> failure-injector.log 2>&1\n"%node.objid
        cfg += "./run_failure_injector.py --node n%d >failure-injector.log 2>&1\n"%node.objid
        cfg += 'echo "Failure injector finished."\n'
        return cfg

# this line is required to add the above class to the list of available services
addservice(FailureInjector)

