#
# CORE
# Copyright (c)2010-2012 the Boeing Company.
# See the LICENSE file included in this distribution.
#
''' Sample user-defined service.
'''

import os
import networkx as nx

from core.service import CoreService, addservice
from core.misc.ipaddr import IPv4Prefix, IPv6Prefix

class FixedRoutes(CoreService):
    ''' Fixed routes for static ad-hoc networks.
    '''
    # a unique name is required, without spaces
    _name = "FixedRoutes"
    # you can create your own group here
    _group = "SEEP"
    # list of other services this service depends on
    _depends = ()
    # per-node directories
    _dirs = ()
    # generated files (without a full path this file goes in the node's dir,
    #  e.g. /tmp/pycore.12345/n1.conf/)
    _configs = ('fixed_routes.sh', )
    # this controls the starting order vs other enabled services
    _startindex = 45
    # list of startup commands, also may be generated during startup
    _startup = ('sh fixed_routes.sh',)
    # list of shutdown commands
    _shutdown = ()
    _validate = ()

    @classmethod
    def generateconfig(cls, node, filename, services):
        ''' Return a string that will be written to filename, or sent to the
            GUI for user customization.
        '''
        cfg = "#!/bin/sh\n"
        cfg += "# auto-generated by MyService (sample.py)\n"
        cfg += "cp ../fixed_routes/fixed_routes_n%d.sh .\n"%node.objid
        cfg += "./fixed_routes_n%s.sh\n"%node.objid

        return cfg

# this line is required to add the above class to the list of available services
addservice(FixedRoutes)

